apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: juicefs
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: "myjfs"
  metaurl: "redis://:{password}@{host}:{port}/1"
  storage: ""
  bucket: ""
  access-key: ""
  secret-key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret-2
  namespace: juicefs
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: "myjfs2"
  metaurl: "redis://:{password}@{host}:{port}/2"
  storage: ""
  bucket: ""
  access-key: ""
  secret-key: ""