apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: juicefs
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: ""
  metaurl: ""
  storage: ""
  bucket: ""
  access-key: ""
  secret-key: ""