apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-pvc-1
  namespace: juicefs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: juicefs-sc