apiVersion: v1
kind: Pod
metadata:
  name: test-juicefs-app
  namespace: juicefs
spec:
  containers:
  - args:
    - -c
    - while true; do echo $(date -u) >> /data/out.txt; sleep 10; done
    command:
    - /bin/sh
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/centos:centos7.9.2009
    name: app
    volumeMounts:
    - mountPath: /data
      name: juicefs-pv
      # 必须配置好传播，以防 mount pod 异常以后，挂载点无法自动恢复
      mountPropagation: HostToContainer
  volumes:
  - name: juicefs-pv
    persistentVolumeClaim:
      claimName: juicefs-pvc-1